version: '3.7'

services:

  mysql:
    container_name: mysql
    restart: always
    image: mysql:8.0.16
    environment:
      MYSQL_DATABASE: 'webshop'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    volumes:
      - db-volume:/var/lib/mysql


  spring-server:
    container_name: spring-server
    build: ./
    depends_on:
      - mysql
    restart: on-failure:5
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    ports:
      - '443:443'
    links:
      - mysql


volumes:
  db-volume: